# Generated by Django 5.1.4 on 2024-12-15 21:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_task_descript_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='invite_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.trip', verbose_name='Путешествие'),
        ),
    ]
