# Generated by Django 5.1.4 on 2024-12-16 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_trip_invite_code_alter_task_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название места')),
                ('date', models.DateField(verbose_name='Дата посещения')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время посещения')),
                ('category', models.CharField(choices=[('hotel', 'Отель'), ('restaurant', 'Ресторан'), ('attraction', 'Достопримечательность')], max_length=50, verbose_name='Категория')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='main.trip')),
            ],
        ),
    ]
