# Generated by Django 5.1.4 on 2024-12-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_routeitem_vote_delete_routepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeitem',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='route_items', to='main.trip'),
            preserve_default=False,
        ),
    ]
