# Generated by Django 5.1.4 on 2024-12-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_routeitem_route_alter_routeitem_trip_routevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
