# Generated by Django 5.1.4 on 2024-12-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_route_approved_remove_routeitem_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
