# Generated by Django 5.1.4 on 2024-12-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_routeitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание маршрута'),
        ),
    ]
