# Generated by Django 5.1.4 on 2024-12-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_route_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeitem',
            name='price',
        ),
    ]
