# Generated by Django 5.1.4 on 2024-12-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_routeitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
